#!/bin/sh

distribution=$1
dist_version=$2
package=$3
distdir=$4

if test -f $distdir.tar.gz; then
  sha1sum $distdir.tar.gz > $distdir.tar.gz.sha1
fi
if test -f $distdir.tar.bz2; then
  sha1sum $distdir.tar.bz2 > $distdir.tar.bz2.sha1
fi

